<a href="https://colab.research.google.com/github/padfoot194/Pytorch_Learning/blob/main/Tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
my_torch= torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Reshape and view
my_torch= my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#Reshape if we don't know the number of items
my_torch2= torch.arange(12)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
my_torch2.reshape(3,-1)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
my_torch3= torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch4= my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
#So, view and reshape are kinda similar

In [ ]:
#With reshape and view, they will update
my_torch5= torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch6= my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch5[1]= 69
my_torch5

tensor([ 0, 69,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
my_torch6

tensor([[ 0, 69,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [ ]:
#Slices
my_torch7= torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Grab a specific item
my_torch7[7]

tensor(7)

In [ ]:
#So this doesn't grab a number. Rather it grabs a tensor.

In [ ]:
#Grab a slice
my_torch8= my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [ ]:
#To return a column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])